<?php

namespace App\Http\Models;

use App\Http\Observers\Models\LabelsObserver;
use Illuminate\Database\Eloquent\Model;

/**
* @property integer $id 
* @property string $label_name 标签名字
* @property datetime $deleted_at 
* @property datetime $created_at 
* @property datetime $updated_at 
*/
class Labels extends Model
{

    // if connection is empty ,use default connection
    protected $connection = '';

    protected $table = 'labels';

    // default values
    protected $attributes = [
        
        'label_name' => '',
        'deleted_at' => '',
        'created_at' => '',
        'updated_at' => '',

    ];

    // converting attributes to common data types. like 'is_admin' => 'boolean',
    protected $casts = [

    ];

    public $rules = [
        
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(LabelsObserver::class);
    }
}
