<?php

namespace App\Http\Models;

use App\Http\Observers\Models\OrdersObserver;
use Illuminate\Database\Eloquent\Model;

/**
* @property integer $id 
* @property integer $user_id 
* @property boolean $state 1:已完成支付
2:待支付
3:已失效
* @property decimal $order_price 
* @property integer $t_id 商品id
* @property datetime $deleted_at 
* @property datetime $created_at 
* @property datetime $updated_at 
*/
class Orders extends Model
{

    // if connection is empty ,use default connection
    protected $connection = '';

    protected $table = 'orders';

    // default values
    protected $attributes = [
        
        'user_id' => '',
        'state' => '',
        'order_price' => '0.01',
        't_id' => '',
        'deleted_at' => '',
        'created_at' => '',
        'updated_at' => '',

    ];

    // converting attributes to common data types. like 'is_admin' => 'boolean',
    protected $casts = [

    ];

    public $rules = [
        
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(OrdersObserver::class);
    }
}
