<?php

namespace App\Http\Models;

use App\Http\Observers\Models\TreasureObserver;
use Illuminate\Database\Eloquent\Model;

/**
* @property integer $id 
* @property string $img_url 
* @property string $name 
* @property text $description 
* @property decimal $price 价钱
* @property integer $inventory 库存量
* @property boolean $state 1:正常售卖
2:已经售馨
3:预告状态
* @property datetime $deleted_at 
* @property string $author 作者
* @property string $referrer 推荐人
* @property string $brand_party 品牌方
* @property string $chain_part 链方
* @property integer $label 宝贝分类
* @property datetime $created_at 
* @property datetime $updated_at 
*/
class Treasure extends Model
{

    // if connection is empty ,use default connection
    protected $connection = '';

    protected $table = 'treasure';

    // default values
    protected $attributes = [
        
        'img_url' => '',
        'name' => '',
        'description' => '',
        'price' => '0.01',
        'inventory' => '0',
        'state' => '',
        'deleted_at' => '',
        'author' => '',
        'referrer' => '',
        'brand_party' => '',
        'chain_part' => '',
        'label' => '',
        'created_at' => '',
        'updated_at' => '',

    ];

    // converting attributes to common data types. like 'is_admin' => 'boolean',
    protected $casts = [

    ];

    public $rules = [
        
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(TreasureObserver::class);
    }
}
