<?php

namespace App\Http\Models;

use App\Http\Observers\Models\UserObserver;
use Illuminate\Database\Eloquent\Model;

/**
* @property integer $id 
* @property string $phone 手机号
* @property string $password 
* @property boolean $is_real_name 是否实名 0：否 1 ：是
* @property decimal $balance 余额
* @property string $nick_name 昵称
* @property string $invite_code 邀请码
* @property datetime $deleted_at 
* @property datetime $created_at 
* @property datetime $updated_at 
*/
class User extends Model
{

    // if connection is empty ,use default connection
    protected $connection = '';

    protected $table = 'user';

    // default values
    protected $attributes = [
        
        'phone' => '',
        'password' => '',
        'is_real_name' => '0',
        'balance' => '0.00',
        'nick_name' => '',
        'invite_code' => '',
        'deleted_at' => '',
        'created_at' => '',
        'updated_at' => '',

    ];

    // converting attributes to common data types. like 'is_admin' => 'boolean',
    protected $casts = [

    ];

    public $rules = [
        
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(UserObserver::class);
    }
}
